# Generated by Django 5.1.3 on 2024-11-09 12:37

import django.db.models.deletion
import django.utils.timezone
import sqli_api.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, verbose_name='ФИО')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('study_group', models.CharField(max_length=50, verbose_name='Номер группы')),
                ('group', models.CharField(default='student', max_length=120, verbose_name='Группа')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('verified', models.BooleanField(default=False, verbose_name='Подтвержден')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Статус персонала')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Суперпользователь')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=sqli_api.models.generate_unique_lab_name)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('url', models.URLField(blank=True, null=True, unique=True)),
                ('secret_hash', models.CharField(max_length=1024)),
                ('expired_seconds', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_started', models.DateTimeField(null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('date_done', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Создается', 'Создается'), ('Ошибка создания', 'Ошибка создания'), ('Выполняется', 'Выполняется'), ('Останавливается', 'Останавливается'), ('Остановлена', 'Остановлена')], default='Создается', max_length=50)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
