version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=sqli_user
      - POSTGRES_PASSWORD=sqli_pass
      - POSTGRES_DB=sqli_lab
#    volumes:
#      - pg_data:/var/lib/postgresql/data
#
#volumes:
#  pg_data:
