version: "3.8"

services:
  migrator:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: migrator
    restart: "no"
    command: ["python", "manage.py", "migrate"]
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ../.env.example

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=sqli_user
      - POSTGRES_PASSWORD=sqli_pass
      - POSTGRES_DB=sqli_lab
      - PGUSER=sqli_user
    user: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d sqli_lab -U sqli_user"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s
