version: "3.8"

services:
  qsli_lab:
    image: sqli-lab-backend:latest
    restart: always
    container_name: sqli_lab
    networks:
      - sqli_lab
    command: [ "gunicorn", "--bind", "0.0.0.0:8000", "--workers", "4", "sqli_lab.wsgi:application" ]
    depends_on:
      migrator:
        condition: service_completed_successfully
    env_file:
      - ../.env.example
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sqli_lab.rule=PathPrefix(`/`)"
      - "traefik.http.services.sqli_lab.loadbalancer.server.port=8000"

  migrator:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: migrator
    restart: "no"
    command: ["python", "manage.py", "migrate"]
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - sqli_lab
    env_file:
      - ../.env.example

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file:
      - ../.env.example
    networks:
      - sqli_lab
    ports:
      - "5432:5432"
    user: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d sqli_lab -U sqli_user"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s
#    volumes:
#      - ../init.sql:/docker-entrypoint-initdb.d/init.sql:ro

networks:
  sqli_lab:
    external: true
